name: MessageFilter
main: me.fromgate.messagefilter.MessageFilter
version: ${project.version}
api-version: ${spigot.api.version}
author: fromgate, fromgate@gmail.com
depend: [ProtocolLib]
commands:
   msgfilter:
      aliases: [mfilter, filter]
      description: Message Filter command
      usage: 
           /msgfilter help